import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { EvidenceClient, saveJson } from './lib/source_access.mjs';
import { extractEvidence } from './lib/source_adapters.mjs';
import { resourceContext } from './prepare_daily_brief.mjs';
import { readFile } from 'node:fs/promises';
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const url = process.argv[2];
if (!url) throw new Error('Usage: read_source.mjs HTTPS_URL [--refresh]');
const blocked = resourceContext(await readFile(path.join(root, 'resources.html'), 'utf8')).blockedResourceDomains;
const host = new URL(url).hostname.replace(/^www\./, '');
if (blocked.some(h => host === h || host.endsWith(`.${h}`))) throw new Error('Source is blocked in resources.html');
const client = new EvidenceClient({ cacheDir: path.join(root, '.daily-work/evidence') });
const result = await client.get(url, { refresh: process.argv.includes('--refresh') });
const { body, ...metadata } = result;
const evidence = result.ok ? extractEvidence(body, result.finalUrl) : null;
const record = { ...metadata, evidence, metrics: client.metrics };
await saveJson(result.bodyFile?.replace(/\.body$/, '.extracted.json') || path.join(root, '.daily-work/evidence/failure.json'), record);
console.log(JSON.stringify(record, null, 2));
if (!result.ok) process.exitCode = 1;
